export const posts = [
  {
    "id": 1,
    "title": "Mudando tema de uma aplicação React utilizando Styled Components e ContextAPI",
    "subtitle": "Nessa anotação está descrito como realizar a mundança de tema da aplicação de uma forma simples",
    "image": "https://mochikit.com/wp-content/uploads/2019/01/react-js.jpg",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus dignissim sagittis. Quisque tincidunt arcu at cursus gravida. Quisque eget libero vel urna bibendum mollis eu eget metus. Morbi cursus lacus sit amet metus gravida, a tristique justo lacinia. Ut ultricies, sapien eu gravida ullamcorper, tortor erat placerat tortor, ullamcorper egestas orci sem at neque. Etiam eleifend ante sed ipsum congue ornare. Fusce mauris libero, vestibulum et cursus mollis, consectetur ut eros. Maecenas et ornare turpis. Pellentesque sed lacus id erat convallis tempus. Etiam convallis massa vel ornare venenatis. Nunc vel massa lorem. Cras luctus vestibulum scelerisque. Morbi fermentum egestas nisl, id rhoncus justo. In hac habitasse platea dictumst. Nullam ut urna ut ex pulvinar consequat at ac sem. Nam feugiat est ut eleifend rhoncus. Pellentesque malesuada ligula in convallis efficitur. Nulla facilisi. Ut congue egestas magna, quis lobortis lorem venenatis varius. Cras sed elementum erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur ultricies purus nisi, hendrerit porttitor nibh consequat quis. Vestibulum eleifend ut dui nec condimentum. Ut imperdiet lacus ut lectus tristique, sit amet porta magna bibendum. Duis posuere quam eu metus bibendum posuere. Phasellus a pulvinar diam. Pellentesque ultrices, est ac pulvinar volutpat, arcu nulla maximus odio, quis aliquam sapien ligula vitae justo. Pellentesque commodo, dolor in faucibus laoreet, ex neque bibendum libero, sit amet mollis leo enim nec nisi. Etiam nec orci ut massa ullamcorper pulvinar eu in tortor. Sed porta dictum velit nec placerat. Quisque ipsum urna, ultricies at accumsan quis, pulvinar eu justo. Sed scelerisque eros vel cursus eleifend. Donec non dolor quis tortor fringilla egestas. Curabitur feugiat erat vitae erat condimentum, vel fermentum neque imperdiet. Duis dapibus ullamcorper aliquet. Integer aliquam rutrum nisi. Fusce vehicula sapien id leo mattis sodales. Donec luctus mi eu augue vestibulum ultrices. Aenean condimentum id risus nec eleifend. Praesent varius metus sed magna tincidunt dignissim. Nulla mi velit, aliquet sed velit ac, faucibus ullamcorper urna. Aenean tincidunt pulvinar leo et convallis. Mauris eros lectus, pretium in sem at, sodales dapibus nunc. Morbi ornare condimentum tincidunt. Proin luctus feugiat lacus, mollis accumsan eros condimentum eu."
  },
  {
    "id": 2,
    "title": "Mudando tema de uma aplicação React utilizando Styled Components e ContextAPI",
    "subtitle": "Nessa anotação está descrito como realizar a mundança de tema da aplicação de uma forma simples",
    "image": "https://mochikit.com/wp-content/uploads/2019/01/react-js.jpg",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus dignissim sagittis. Quisque tincidunt arcu at cursus gravida. Quisque eget libero vel urna bibendum mollis eu eget metus. Morbi cursus lacus sit amet metus gravida, a tristique justo lacinia. Ut ultricies, sapien eu gravida ullamcorper, tortor erat placerat tortor, ullamcorper egestas orci sem at neque. Etiam eleifend ante sed ipsum congue ornare. Fusce mauris libero, vestibulum et cursus mollis, consectetur ut eros. Maecenas et ornare turpis. Pellentesque sed lacus id erat convallis tempus. Etiam convallis massa vel ornare venenatis. Nunc vel massa lorem. Cras luctus vestibulum scelerisque. Morbi fermentum egestas nisl, id rhoncus justo. In hac habitasse platea dictumst. Nullam ut urna ut ex pulvinar consequat at ac sem. Nam feugiat est ut eleifend rhoncus. Pellentesque malesuada ligula in convallis efficitur. Nulla facilisi. Ut congue egestas magna, quis lobortis lorem venenatis varius. Cras sed elementum erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur ultricies purus nisi, hendrerit porttitor nibh consequat quis. Vestibulum eleifend ut dui nec condimentum. Ut imperdiet lacus ut lectus tristique, sit amet porta magna bibendum. Duis posuere quam eu metus bibendum posuere. Phasellus a pulvinar diam. Pellentesque ultrices, est ac pulvinar volutpat, arcu nulla maximus odio, quis aliquam sapien ligula vitae justo. Pellentesque commodo, dolor in faucibus laoreet, ex neque bibendum libero, sit amet mollis leo enim nec nisi. Etiam nec orci ut massa ullamcorper pulvinar eu in tortor. Sed porta dictum velit nec placerat. Quisque ipsum urna, ultricies at accumsan quis, pulvinar eu justo. Sed scelerisque eros vel cursus eleifend. Donec non dolor quis tortor fringilla egestas. Curabitur feugiat erat vitae erat condimentum, vel fermentum neque imperdiet. Duis dapibus ullamcorper aliquet. Integer aliquam rutrum nisi. Fusce vehicula sapien id leo mattis sodales. Donec luctus mi eu augue vestibulum ultrices. Aenean condimentum id risus nec eleifend. Praesent varius metus sed magna tincidunt dignissim. Nulla mi velit, aliquet sed velit ac, faucibus ullamcorper urna. Aenean tincidunt pulvinar leo et convallis. Mauris eros lectus, pretium in sem at, sodales dapibus nunc. Morbi ornare condimentum tincidunt. Proin luctus feugiat lacus, mollis accumsan eros condimentum eu."
  }
]